import { z } from 'zod';

/**
 * Identifiers are prefixed and generated by the database. Validating the shape
 * here keeps malformed IDs out of queries and makes path parameters explicit.
 */
const idPattern = (prefix: string) => new RegExp(`^${prefix}_[0-9a-f]{32}$`);

export const idSchema = (prefix: string) =>
  z.string().regex(idPattern(prefix), `Expected a ${prefix}_ identifier`);

export const userIdSchema = idSchema('usr');
export const organizationIdSchema = idSchema('org');
export const memberIdSchema = idSchema('mem');
export const invitationIdSchema = idSchema('inv');
export const requestIdSchema = idSchema('req');
export const receiptIdSchema = idSchema('rcpt');
export const credentialIdSchema = idSchema('cred');
export const challengeIdSchema = idSchema('chl');

/**
 * Emails are lowercased and trimmed before validation so that the same address
 * always produces the same stored value and the same normalized payload
 * (PRD FR-007).
 */
export const emailSchema = z
  .string()
  .trim()
  .toLowerCase()
  .email('Enter a valid email address')
  .max(254);

/** Trimmed, Unicode-normalized free text. */
export const normalizedText = (max: number) =>
  z
    .string()
    .transform((value) => value.normalize('NFC').trim())
    .pipe(z.string().max(max));

export const requiredText = (max: number, message = 'This field is required') =>
  z
    .string()
    .transform((value) => value.normalize('NFC').trim())
    .pipe(z.string().min(1, message).max(max));

/** ISO 4217 alphabetic currency code, always stored uppercase. */
export const currencySchema = z
  .string()
  .trim()
  .toUpperCase()
  .regex(/^[A-Z]{3}$/, 'Enter a three-letter currency code such as USD');

/** Calendar date with no time component, as `YYYY-MM-DD`. */
export const isoDateSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, 'Enter a date as YYYY-MM-DD')
  .refine((value) => !Number.isNaN(Date.parse(`${value}T00:00:00.000Z`)), 'Enter a real date');

/** Monetary amounts are integers in minor units, never floats (PRD FR-007). */
export const amountMinorSchema = z
  .number()
  .int('Enter a whole amount')
  .positive('Enter an amount greater than zero')
  .max(Number.MAX_SAFE_INTEGER);

/** Last four digits of an account identifier. Full numbers are not collected. */
export const lastFourSchema = z
  .string()
  .trim()
  .regex(/^\d{4}$/, 'Enter the last four digits');

export const paginationSchema = z.object({
  cursor: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(25),
});

export type Pagination = z.infer<typeof paginationSchema>;

/**
 * Idempotency key for consequential writes (PRD section 21). Clients generate
 * it; the server uses it to collapse retries rather than to authorize anything.
 */
export const idempotencyKeySchema = z.string().trim().min(8).max(200);
